SELECT X5_FILIAL,X5_TABELA,X5_CHAVE FROM SX5990
WHERE D_E_L_E_T_ = ' '
GROUP BY X5_FILIAL,X5_TABELA,X5_CHAVE
HAVING COUNT(*) > 1


WITH DUPLICATES AS(
SELECT X5_FILIAL,X5_TABELA,X5_CHAVE,ROW_NUMBER() OVER (PARTITION BY X5_FILIAL,X5_TABELA,X5_CHAVE ORDER BY X5_FILIAL,X5_TABELA,X5_CHAVE) AS ROWNUM
FROM SX5990
)
DELETE FROM DUPLICATES WHERE ROWNUM > 1

