SELECT X6_CONTEUD, R_E_C_N_O_, * FROM SX6040 WHERE X6_FIL+X6_VAR IN (
SELECT X6_FIL+X6_VAR FROM SX6040 WHERE D_E_L_E_T_ = '' GROUP BY X6_FIL+X6_VAR HAVING COUNT(*) > 1)
AND D_E_L_E_T_ = '' ORDER BY 4
